# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a306adf39c55e84112553f03faaf00beea947d667cd8648764790fa572914bbf454947960396239772cd2bad226b7acb48bafa3b23640e6cc284c990c2a5aaa

test:
  secret_key_base: 9b889237a9af7436c6f15c0ce1d371a65751484bb99939717525a119fafefff99775f9add75bf4dededb859cc02b7c556e054a66cf0c0ec1913204b500fe7783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
